### ISSUE TITLE
nicehash grin Connection Error: Write timeout

### ISSUE THREAD

**Issue by psynauty** [nicehash/Specifications#11]
Switched to grincuckaroo29.eu.nicehash.com from sparkpool using gminer and I get "Connection Error: Write timed out" right after "Authorised on Stratum Server

**Comment by pit55** [comment]
Yes, when i connect direct nicehash evrything works good, but if i connect miningrigrentals and i set the nicehash pool, i received this message also. Connection Error: Write timed out.
Only Grin29, BEAM works good !
