### ISSUE TITLE
Shares being rejected with "share above target"

### ISSUE THREAD

**Issue by argonatorUberTF** [nicehash/Specifications#17]
I noticed in the logs of both PhoenixMiner, LOLminer, and sometimes in Nicehash Quickminer I get these status return texts with rejected shares.  Even though the ping time is down in the <30 ms timeframe.
The pool server, nicehash.com is handing out work with a difficulty setting in the 629 MH range and the miner application is solving for the task.
So why is the share invalid, rejected, when the work was assigned with your stratum spec?
A share above the target would exceed the difficulty and possibly be a super share spanning beyond the number of assigned miners. It could also be a complete solve of the block.
See attached log excerpts:
------------------------
2021.05.19:10:49:51.129: main *** 10:52 *** 5/19 10:49 **************************************
2021.05.19:10:49:51.130: main Eth: Mining ETH on daggerhashimoto.usa-west.nicehash.com:3353 for 10:52
2021.05.19:10:49:51.130: main Eth: Accepted shares 3887 (7 stales), rejected shares 21 (7 stales)
2021.05.19:10:49:51.130: main Eth: Incorrect shares 0 (0.00%), est. stales percentage 0.30% 
2021.05.19:10:49:51.130: main Eth: Maximum difficulty of found share: 1558.8 GH (!)
2021.05.19:10:49:51.130: main Eth: Average speed (5 min): 36.515 MH/s
2021.05.19:10:49:51.130: main Eth: Effective speed: 34.98 MH/s; at pool: 34.80 MH/s
2021.05.19:10:49:51.130: main  
2021.05.19:10:49:51.992: main Eth speed: 36.453 MH/s, shares: 3887/21/0, time: 10:52
2021.05.19:10:49:54.545: GPU1 Eth: GPU1: ETH share found!
2021.05.19:10:49:54.545: eths Eth: Send: {"id":4,"method":"mining.submit","params": ["3Evg9MTNPWvyiZPG8KPA8KEvNWh9i3wboD.rigN","00000000924f90dc","006bf338ef"]}

2021.05.19:10:49:54.545: eths Eth: Share actual difficulty: 526 MH
2021.05.19:10:49:54.565: eths Eth: Received: {"id":4,"result":false,"error":[1,"Share above target."]}
2021.05.19:10:49:54.565: eths Eth: Share rejected in 20 ms
2021.05.19:10:49:56.138: eths Eth: Received: {"id":null,"method":"mining.set_extranonce","params":["256de6"]}
2021.05.19:10:49:56.138: eths Eth: Extranonce set to 256de6
2021.05.19:10:49:56.141: eths Eth: Received: {"id":null,"method":"mining.set_difficulty","params":[0.1]}
2021.05.19:10:49:56.141: eths Eth: Difficulty set to 0.1
2021.05.19:10:49:56.142: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90dd","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","30ab1b19c26c6d3346cf759772dbd09a2b8035479958dc8a521ba9738caaaef9",true]}
2021.05.19:10:49:56.142: eths Eth: New job #30ab1b19 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:49:56.782: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90de","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","4e6d3116e43e9d5a3db9c029cb90f7a07a7c7daae844dea4264e820d2407cf7a",false]}
2021.05.19:10:49:56.782: eths Eth: New job #4e6d3116 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:49:57.151: main Eth speed: 36.479 MH/s, shares: 3887/22/0, time: 10:52
2021.05.19:10:49:57.788: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90df","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","36bf90dcba96e56581b5b1103ffb8afc47b836c112a58693dff1d622d0843c5c",false]}
2021.05.19:10:49:57.788: eths Eth: New job #36bf90dc from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:49:58.207: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e0","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","aaf149b92f58faebc560b4fb051627b463d42ce13d305f7bf40d7dbf1882a33a",true]}
2021.05.19:10:49:58.207: eths Eth: New job #aaf149b9 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:49:59.155: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e1","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","0ff46943154d5a4175b072bb117d80a46c3c0c1c697eda9a33b0bc9a124ffd9d",false]}
2021.05.19:10:49:59.156: eths Eth: New job #0ff46943 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:00.164: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e2","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","115b18a015ea914d1dcd2cb24fc53cdf3968baed5ff0ba7b3cdcaf7674fda964",false]}
2021.05.19:10:50:00.164: eths Eth: New job #115b18a0 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:01.175: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e3","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","b36fa422b52fa8d111a5f4002b46d6258068e0b9ad2ddbd648dd4c3b215e5a62",false]}
2021.05.19:10:50:01.175: eths Eth: New job #b36fa422 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:02.170: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e4","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","1e648f28a4c98262ce6dea51133beb18d1a8d839ab8b1afba939c691112bb082",false]}
2021.05.19:10:50:02.170: eths Eth: New job #1e648f28 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:02.277: main Eth speed: 36.484 MH/s, shares: 3887/22/0, time: 10:52
2021.05.19:10:50:02.919: main GPU1: 64C 100% 209W
GPUs power: 209.2 W
2021.05.19:10:50:03.154: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e5","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","f736510224e6485a06db3b54f06f927a29ab24c32fd619c985131d7f9639ea74",false]}
2021.05.19:10:50:03.154: eths Eth: New job #f7365102 from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:04.170: eths Eth: Received: {"id":null,"method":"mining.notify","params":["00000000924f90e6","3646e1f9abad7750d559c03326ae5841c98e2fff3ee4ef7e1bc354b4499c946d","d07d5fdba5f2b4627059f2e9026b1dd8ae31413c14aae0f5a08c25233e1a3982",false]}
2021.05.19:10:50:04.170: eths Eth: New job #d07d5fdb from daggerhashimoto.usa-west.nicehash.com:3353; diff: 429MH
2021.05.19:10:50:04.617: GPU1 Eth: GPU1: ETH share found!
2021.05.19:10:50:04.617: eths Eth: Send: {"id":4,"method":"mining.submit","params": ["3Evg9MTNPWvyiZPG8KPA8KEvNWh9i3wboD.rigN","00000000924f90e6","0019b71f94"]}

2021.05.19:10:50:04.617: eths Eth: Share actual difficulty: 691 MH
2021.05.19:10:50:04.637: eths Eth: Received: {"id":4,"result":true,"error":null}
2021.05.19:10:50:04.637: eths Eth: Share accepted in 20 ms

**Comment by SomethingGettingWrong** [comment]
Having this same issue!
![image](https://user-images.githubusercontent.com/36722911/118898660-affa6e00-b8d2-11eb-984c-861eabda7ee9.png)

**Comment by SomethingGettingWrong** [comment]
litearly it sends out work then the job dissapears! then it says stale.. 50 ms come ON!!!!
