### ISSUE TITLE
Please explain CryptoNight spec

### ISSUE THREAD

**Issue by Vanzent** [nicehash/Specifications#2]
IV. Real world scenario |  
-- | --
  | -----------------------
  |  
  | NiceHash server sends following job to miner:
  |  
  | {"jsonrpc":"2.0","method":"job","params":{"blob":
  | "0100f2fbf1ae05e778512836d3268c95b53004002f8bf0b4e591dd6c903e3620
  | 12b60a6eaf64cc0000003026f3436334364896a4dce0864798a16a137b9b5dc47
  | a39f00a3a75077e8f14d102","job_id":"333972526853904",
  | "target":"711b0d00"}}
  |  
  | In this case; inside blob, 4 bytes of "00000000" are replaced with
  | "000000030" by NiceHash. NiceHash gives miner byte "03".
  |  
  | Miner sends found share:
  |  
  | {"method": "submit", "params": {"id": "843393400195054", "job_id":
  | "333972526853904", "nonce": "95565503", "result":
  | "1b3f259aafb85c553198c2ad92392e816a8c030ac84305b89c932c8723bd0800"},
  | "id":4}
  |  
  | Nonce ends with byte "03" which is correct. Any other last byte
  | of nonce would cause share above target.

I not understand. Why in json 4 bytes is 00 00 00 30. Next you wrote 00 00 00 030. 030? Where you take that? In first json nicehash byte is 30, not 03. Pleas explain.

**Comment by Kukunin** [comment]
It's not clear to me as well.
