### ISSUE TITLE
Ethereum stratum question

### ISSUE THREAD

**Issue by rjl493456442** [nicehash/Specifications#3]
In the Ethereum stratum mining protocol, it said the `Target` field is no necessary been included since the target can be calculated by miner itself.

My question is how can miner calculate the target? The difficulty is depends on the parent block difficulty and the interval between parent block and current mining block. Those two are totally transparent for miner.

**Comment by jgillich** [comment]
Difficulty in terms of Stratum is not the same as network difficulty, see: https://bitcoin.stackexchange.com/a/61726

I have a [Go implementation](https://github.com/jgillich/blockforge/blob/af3767e58acc27f891d22f5ebe43a482167aa519/algo/ethash/work.go#L24) that converts target to difficulty that I ported over from cpp-ethereum. Can't really tell you much about it though.
